# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhContribs < Formula
  desc "Your GitHub contribution rhythm, in the terminal"
  homepage "https://github.com/Josef-Hlink/gh-contribs"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.0.1/gh-contribs_0.0.1_darwin_amd64.tar.gz"
      sha256 "d13b1f4c037e205464b69d8cad98ec79572dabb8066ed2fa078cd8dd7e7abeac"

      define_method(:install) do
        bin.install "gh-contribs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.0.1/gh-contribs_0.0.1_darwin_arm64.tar.gz"
      sha256 "1f0e0e0bec4646acbe847a0f9167c3c195088cf0b2947fec67a125c642c23b98"

      define_method(:install) do
        bin.install "gh-contribs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.0.1/gh-contribs_0.0.1_linux_amd64.tar.gz"
      sha256 "a82d4d0b756ee3b5f7ced7d138fa0b37fc28123841aa264a681b949a28b11db1"
      define_method(:install) do
        bin.install "gh-contribs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.0.1/gh-contribs_0.0.1_linux_arm64.tar.gz"
      sha256 "f18acb78acf46a8c5f4f42f5745faa16c8ccaf73d80a7f0e9b9a3e9735467b74"
      define_method(:install) do
        bin.install "gh-contribs"
      end
    end
  end

  test do
    system "#{bin}/gh-contribs", "--version"
  end
end
