# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twin < Formula
  desc "tmux workspace manager driven by TOML recipes"
  homepage "https://github.com/Josef-Hlink/twin"
  version "0.2.0"
  license "MIT"

  depends_on "fzf"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.0/twin_0.2.0_darwin_amd64.tar.gz"
      sha256 "6f59a1c0c7b3686d6bd63fe8bf93e6dbe8d937b445cd76d17e3ae3b91ff0168e"

      define_method(:install) do
        bin.install "twin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.0/twin_0.2.0_darwin_arm64.tar.gz"
      sha256 "211914840ca460bf7782075b52b678458218fb1f0e6965fea1b951d097a770d3"

      define_method(:install) do
        bin.install "twin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.0/twin_0.2.0_linux_amd64.tar.gz"
      sha256 "e495798f00490c887f3b6aa822d317aaf4e879bc5b13781a1d0a6c4f827aa9a1"
      define_method(:install) do
        bin.install "twin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.0/twin_0.2.0_linux_arm64.tar.gz"
      sha256 "2140141bdb6057d72ea3ee4e13f0d2bb90f0d683ab7c00ab0bbee9c10e01378c"
      define_method(:install) do
        bin.install "twin"
      end
    end
  end

  test do
    system "#{bin}/twin", "--version"
  end
end
