# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twin < Formula
  desc "tmux workspace manager driven by TOML recipes"
  homepage "https://github.com/Josef-Hlink/twin"
  version "0.2.4"
  license "MIT"

  depends_on "fzf"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.4/twin_0.2.4_darwin_amd64.tar.gz"
      sha256 "f264e90abd7ba7035cd193c481a5166d9adad6032edb2cb86cbcc047edd37c9e"

      define_method(:install) do
        bin.install "twin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.4/twin_0.2.4_darwin_arm64.tar.gz"
      sha256 "27e91c8ec9871e04de236774f87ce9c4b7cd82cc63cb690256cad20d570fcc9c"

      define_method(:install) do
        bin.install "twin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.4/twin_0.2.4_linux_amd64.tar.gz"
      sha256 "d4ea4e425965ecb87a9258a228e6d2befe5cf5117abc9531aef96cad34e30ead"
      define_method(:install) do
        bin.install "twin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.4/twin_0.2.4_linux_arm64.tar.gz"
      sha256 "2ad2cc7653b2503d811e901b58c12621f685a6194c615da006f0b074e237378e"
      define_method(:install) do
        bin.install "twin"
      end
    end
  end

  test do
    system "#{bin}/twin", "--version"
  end
end
