# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twin < Formula
  desc "tmux workspace manager driven by TOML recipes"
  homepage "https://github.com/Josef-Hlink/twin"
  version "0.2.1"
  license "MIT"

  depends_on "fzf"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.1/twin_0.2.1_darwin_amd64.tar.gz"
      sha256 "03a064bcd0a0492ce1c70b5720122ba8aa8b99b9130c8dcb6e5f19d17dfe07e4"

      define_method(:install) do
        bin.install "twin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.1/twin_0.2.1_darwin_arm64.tar.gz"
      sha256 "80f8df2e88ff85b470a481c00225183b89229e352d9d9d32cd9eefdce7522e9f"

      define_method(:install) do
        bin.install "twin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.1/twin_0.2.1_linux_amd64.tar.gz"
      sha256 "0b94e57ae532dc5f2369d29e5da1fe0ae705ff5f9d6de75cff0c44ed4bcc224f"
      define_method(:install) do
        bin.install "twin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Josef-Hlink/twin/releases/download/v0.2.1/twin_0.2.1_linux_arm64.tar.gz"
      sha256 "35cd8e1f041cbd9f755463d2f24fab23a0b78687d7b3ce394783373c779d9b6c"
      define_method(:install) do
        bin.install "twin"
      end
    end
  end

  test do
    system "#{bin}/twin", "--version"
  end
end
